# Generated by Django 2.1.7 on 2019-03-27 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190327_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 5, 48, 44, 4547, tzinfo=utc)),
        ),
    ]
