# Generated by Django 2.1.7 on 2019-03-27 06:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190327_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 6, 3, 46, 344576, tzinfo=utc)),
        ),
    ]
