# Generated by Django 2.1.7 on 2019-03-27 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190327_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 9, 27, 46, 998852, tzinfo=utc)),
        ),
    ]
