# Generated by Django 2.1.7 on 2019-03-28 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190327_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 6, 42, 41, 978145, tzinfo=utc)),
        ),
    ]
